version: "3"
services:
  app:
    image: metal3d/ng
    volumes:
      - ./app:/app
    ports:
      - 4200:4200
    privileged: true
    user: 1000:1000
    environment:
      APPNAME: Smile 

  api:
    build: api
    ports:
      - 3000:3000

